[package]
name = "system_network"
version = "0.0.0"
edition = "2021"

[dependencies]
# laminar = "0.5.0"
nalgebra-glm = "0.16.0"
rand = "0.8.5"

game_entity = { path = "../game_entity" }
update_buffer = { path = "../update_buffer" }
